// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using pfe.Models;

namespace pfe.Migrations
{
    [DbContext(typeof(GestContext))]
    [Migration("20210906205352_MyFirstMigration")]
    partial class MyFirstMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.9")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("pfe.Models.Compte", b =>
                {
                    b.Property<int>("CompteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CO")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("CR")
                        .HasColumnType("bit");

                    b.Property<string>("CompteDB")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("DB")
                        .HasColumnType("bit");

                    b.Property<string>("Lib")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OuvertCR")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OuvertDB")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TypeCompte")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CompteId");

                    b.ToTable("Comptes");
                });

            modelBuilder.Entity("pfe.Models.DepBancaire", b =>
                {
                    b.Property<int>("DepBanId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CO")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Date")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Libelle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MVT")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Montant")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NCH")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tiers")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DepBanId");

                    b.ToTable("DepBancaires");
                });

            modelBuilder.Entity("pfe.Models.DepCaisse", b =>
                {
                    b.Property<int>("DepCaiId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CO")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Date")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Libelle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MVT")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Montant")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Recu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tiers")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DepCaiId");

                    b.ToTable("DepCaisses");
                });

            modelBuilder.Entity("pfe.Models.PaymentDetail", b =>
                {
                    b.Property<int>("PaymentDetailId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CardNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CardOwnerName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PaymentDetailId");

                    b.ToTable("PaymentDetails");
                });

            modelBuilder.Entity("pfe.Models.RecBancaire", b =>
                {
                    b.Property<int>("DepBanId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CO")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Date")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Libelle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MVT")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Montant")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NCH")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tiers")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DepBanId");

                    b.ToTable("RecBancaires");
                });

            modelBuilder.Entity("pfe.Models.RecCaisse", b =>
                {
                    b.Property<int>("DepCaiId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CO")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Date")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Libelle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MVT")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Montant")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Recu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tiers")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DepCaiId");

                    b.ToTable("RecCaisses");
                });

            modelBuilder.Entity("pfe.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId");

                    b.ToTable("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
